### ISSUE TITLE
geerlingguy.java dependeny should use "become: yes"

### ISSUE THREAD

**Issue by nwoetzel** [nwoetzel/ansible-role-eclipse#8]
Installing java using yum/apt requires root privileges. this should be reflected in the  meta/main.yml
```
dependencies:
  - name: geerlingguy.java
    become: yes
    version: 1.9.1
```
